/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  84532: {
    ControlStructures: {
      address: "0xD16c6d7DC8e7B35376D881F13A2Cceb992005D73",
      abi: [
        {
          inputs: [
            {
              internalType: "uint256",
              name: "time",
              type: "uint256",
            },
          ],
          name: "AfterHours",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_time",
              type: "uint256",
            },
          ],
          name: "doNotDisturb",
          outputs: [
            {
              internalType: "string",
              name: "message",
              type: "string",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_number",
              type: "uint256",
            },
          ],
          name: "fizzBuzz",
          outputs: [
            {
              internalType: "string",
              name: "fizzBuzz",
              type: "string",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
